insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (1, '饮食', '2', null, 'A');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (2, '卫生医疗费', '2', null, 'B');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (3, '交通', '2', null, 'C');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (4, '孝敬父母', '2', null, 'D');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (5, '通讯电话费', '2', null, 'E');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (6, '文化/娱乐', '2', null, 'F');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (7, '其他开支', '2', null, 'G');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (8, '服饰美容', '2', null, 'H');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (9, '奖金', '1', null, 'I');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (10, '日常开支', '2', null, 'J');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (11, '网购', '2', null, 'K');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (12, '教育培训', '2', null, 'L');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (13, '工资', '1', null, 'M');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (14, '人情往来', '2', null, 'N');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (15, '其他收入', '1', null, 'O');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (16, '借出去', '2', null, 'P');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (17, '晚饭', '2', 'A', 'AA');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (18, '中饭', '2', 'A', 'AB');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (19, '买水等零食', '2', 'A', 'AC');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (20, '早餐', '2', 'A', 'AD');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (21, '超市买东西', '2', 'A', 'AE');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (22, '公共交通', '2', 'C', 'CA');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (23, '春节', '2', 'D', 'DA');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (24, '充话费', '2', 'E', 'EA');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (25, '上网', '2', 'F', 'FA');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (26, '蔬菜水果', '2', 'A', 'AF');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (27, '聚餐请客', '2', 'A', 'AG');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (28, '理发', '2', 'H', 'HA');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (29, '生活用品', '2', 'J', 'JA');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (30, '飞机', '2', 'C', 'CB');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (31, '衣服', '2', 'H', 'HB');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (32, '鞋类', '2', 'H', 'HC');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (33, '买书', '2', 'L', 'LA');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (34, '护肤品', '2', 'H', 'HD');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (35, '火车票', '2', 'C', 'CC');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (36, '差补', '1', 'O', 'OA');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (37, '买菜', '2', 'A', 'AH');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (38, '相机', '2', 'F', 'FB');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (39, '买电影票', '2', 'F', 'FC');
insert into TALLY_TYPE_T (TALLY_TYPE_SNO, TALLY_TYPE_DESC, MONEY_TYPE, PARENT_CODE, TYPE_CODE)
values (40, '其他', '2', 'H', 'HE');
